---
# defaults file for keepalived

keepalived_role: BACKUP

version: 1.3.0

# private IP addresses of ec2 instances
master_ip_address: 10.10.10.1
slave_ip_address: 10.10.10.2

VIP: 10.10.10.10 # instance's secondary IP address
VIP_subnet: 255.255.252.0 # CIDR netmask of a subnet the VIP belongs to

priority_master: 101
priority_slave: 100

keepalived_shared_iface: eth0
keepalived_router_id: 1

interval: 2
fall: 2
rise: 2
